// Code generated by w101-client-go. DO NOT EDIT.
package system

import (
	"github.com/cedws/w101-client-go/proto"
)

type service interface {
	Ping(Ping)
	PingRsp(PingRsp)
}

func (Service) Ping(Ping)       {}
func (Service) PingRsp(PingRsp) {}

func RegisterService(r *proto.MessageRouter, s service) {
	proto.RegisterMessageHandler(r, 1, 1, s.Ping)
	proto.RegisterMessageHandler(r, 1, 2, s.PingRsp)
}

func NewClient(c *proto.Client) Client {
	return Client{c}
}

func (c Client) Ping(m *Ping) error {
	return c.c.WriteMessage(1, 1, m)
}

func (c Client) PingRsp(m *PingRsp) error {
	return c.c.WriteMessage(1, 2, m)
}

type Service struct {
	service
}

type Client struct {
	c *proto.Client
}
type Ping struct {
}

func (s *Ping) Marshal() []byte {
	return []byte{}
}

func (s *Ping) Unmarshal(data []byte) error {
	return nil
}

type PingRsp struct {
}

func (s *PingRsp) Marshal() []byte {
	return []byte{}
}

func (s *PingRsp) Unmarshal(data []byte) error {
	return nil
}
