// Code generated by w101-client-go. DO NOT EDIT.
package extendedbase

import (
	"bytes"
	"encoding/binary"
	"github.com/cedws/w101-client-go/proto"
	"unsafe"
)

type extendedbaseService interface {
	CustomDict(CustomDict)
	CustomRecord(CustomRecord)
	ForceDisconnect(ForceDisconnect)
	RawRecord(RawRecord)
	RawText(RawText)
	ServerMessage(ServerMessage)
}

type ExtendedbaseService struct {
	extendedbaseService
}

type ExtendedbaseClient struct {
	c *proto.Client
}

func (l *ExtendedbaseService) CustomDict(_ CustomDict)           {}
func (l *ExtendedbaseService) CustomRecord(_ CustomRecord)       {}
func (l *ExtendedbaseService) ForceDisconnect(_ ForceDisconnect) {}
func (l *ExtendedbaseService) RawRecord(_ RawRecord)             {}
func (l *ExtendedbaseService) RawText(_ RawText)                 {}
func (l *ExtendedbaseService) ServerMessage(_ ServerMessage)     {}

func RegisterExtendedbaseService(r *proto.MessageRouter, s extendedbaseService) {
	proto.RegisterMessageHandler(r, 2, 1, s.CustomDict)
	proto.RegisterMessageHandler(r, 2, 2, s.CustomRecord)
	proto.RegisterMessageHandler(r, 2, 3, s.ForceDisconnect)
	proto.RegisterMessageHandler(r, 2, 4, s.RawRecord)
	proto.RegisterMessageHandler(r, 2, 5, s.RawText)
	proto.RegisterMessageHandler(r, 2, 6, s.ServerMessage)
}

func NewExtendedbaseClient(c *proto.Client) ExtendedbaseClient {
	return ExtendedbaseClient{c}
}

func (c ExtendedbaseClient) CustomDict(m *CustomDict) error {
	return c.c.WriteMessage(2, 1, m)
}

func (c ExtendedbaseClient) CustomRecord(m *CustomRecord) error {
	return c.c.WriteMessage(2, 2, m)
}

func (c ExtendedbaseClient) ForceDisconnect(m *ForceDisconnect) error {
	return c.c.WriteMessage(2, 3, m)
}

func (c ExtendedbaseClient) RawRecord(m *RawRecord) error {
	return c.c.WriteMessage(2, 4, m)
}

func (c ExtendedbaseClient) RawText(m *RawText) error {
	return c.c.WriteMessage(2, 5, m)
}

func (c ExtendedbaseClient) ServerMessage(m *ServerMessage) error {
	return c.c.WriteMessage(2, 6, m)
}

type CustomDict struct {
}

func (s *CustomDict) Marshal() []byte {
	return []byte{}
}

func (s *CustomDict) Unmarshal(data []byte) error {
	return nil
}

type CustomRecord struct {
}

func (s *CustomRecord) Marshal() []byte {
	return []byte{}
}

func (s *CustomRecord) Unmarshal(data []byte) error {
	return nil
}

type ForceDisconnect struct {
	Message   string
	TimeStamp string
	Type      uint32
}

func (s *ForceDisconnect) Marshal() []byte {
	b := bytes.NewBuffer(make([]byte, 0, 8+len(s.TimeStamp)+len(s.Message)))
	binary.Write(b, binary.LittleEndian, s.Type)
	writeString_2(b, s.TimeStamp)
	writeString_2(b, s.Message)
	return b.Bytes()
}

func (s *ForceDisconnect) Unmarshal(data []byte) error {
	b := bytes.NewReader(data)
	var err error
	if err = binary.Read(b, binary.LittleEndian, &s.Type); err != nil {
		return err
	}
	if s.TimeStamp, err = readString_2(b); err != nil {
		return err
	}
	if s.Message, err = readString_2(b); err != nil {
		return err
	}
	return nil
}

type RawRecord struct {
}

func (s *RawRecord) Marshal() []byte {
	return []byte{}
}

func (s *RawRecord) Unmarshal(data []byte) error {
	return nil
}

type RawText struct {
	Message string
}

func (s *RawText) Marshal() []byte {
	b := bytes.NewBuffer(make([]byte, 0, 2+len(s.Message)))
	writeString_2(b, s.Message)
	return b.Bytes()
}

func (s *RawText) Unmarshal(data []byte) error {
	b := bytes.NewReader(data)
	var err error
	if s.Message, err = readString_2(b); err != nil {
		return err
	}
	return nil
}

type ServerMessage struct {
	Message string
	Modal   uint8
}

func (s *ServerMessage) Marshal() []byte {
	b := bytes.NewBuffer(make([]byte, 0, 3+len(s.Message)))
	binary.Write(b, binary.LittleEndian, s.Modal)
	writeString_2(b, s.Message)
	return b.Bytes()
}

func (s *ServerMessage) Unmarshal(data []byte) error {
	b := bytes.NewReader(data)
	var err error
	if err = binary.Read(b, binary.LittleEndian, &s.Modal); err != nil {
		return err
	}
	if s.Message, err = readString_2(b); err != nil {
		return err
	}
	return nil
}

func writeString_2(b *bytes.Buffer, v string) {
	binary.Write(b, binary.LittleEndian, uint16(len(v)))
	b.WriteString(v)
}

func readString_2(buf *bytes.Reader) (string, error) {
	var length uint16
	if err := binary.Read(buf, binary.LittleEndian, &length); err != nil {
		return "", err
	}
	data := make([]byte, length)
	if _, err := buf.Read(data); err != nil {
		return "", err
	}
	return *(*string)(unsafe.Pointer(&data)), nil
}
