// Code generated by w101-client-go. DO NOT EDIT.
package mg2

import (
	"bytes"
	"encoding/binary"
	"github.com/cedws/w101-client-go/codegen"
	"github.com/cedws/w101-client-go/proto"
)

type service interface {
	MG2Connect(MG2Connect)
	MG2Moved(MG2Moved)
	MG2Rewards(MG2Rewards)
}

func (Service) MG2Connect(MG2Connect) {}
func (Service) MG2Moved(MG2Moved)     {}
func (Service) MG2Rewards(MG2Rewards) {}

func RegisterService(r *proto.MessageRouter, s service) {
	proto.RegisterMessageHandler(r, 43, 1, s.MG2Connect)
	proto.RegisterMessageHandler(r, 43, 2, s.MG2Moved)
	proto.RegisterMessageHandler(r, 43, 3, s.MG2Rewards)
}

func NewClient(c *proto.Client) Client {
	return Client{c}
}

func (c Client) MG2Connect(m *MG2Connect) error {
	return c.c.WriteMessage(43, 1, m)
}

func (c Client) MG2Moved(m *MG2Moved) error {
	return c.c.WriteMessage(43, 2, m)
}

func (c Client) MG2Rewards(m *MG2Rewards) error {
	return c.c.WriteMessage(43, 3, m)
}

type Service struct {
	service
}

type Client struct {
	c *proto.Client
}
type MG2Connect struct {
}

func (s *MG2Connect) Marshal() []byte {
	return []byte{}
}

func (s *MG2Connect) Unmarshal(data []byte) error {
	return nil
}

type MG2Moved struct {
}

func (s *MG2Moved) Marshal() []byte {
	return []byte{}
}

func (s *MG2Moved) Unmarshal(data []byte) error {
	return nil
}

type MG2Rewards struct {
	GameName string
	Score    int32
}

func (s *MG2Rewards) Marshal() []byte {
	b := bytes.NewBuffer(make([]byte, 0, 6+len(s.GameName)))
	binary.Write(b, binary.LittleEndian, s.Score)
	codegen.WriteString(b, s.GameName)
	return b.Bytes()
}

func (s *MG2Rewards) Unmarshal(data []byte) error {
	b := bytes.NewReader(data)
	var err error
	if err = binary.Read(b, binary.LittleEndian, &s.Score); err != nil {
		return err
	}
	if s.GameName, err = codegen.ReadString(b); err != nil {
		return err
	}
	return nil
}
