// Code generated by w101-client-go. DO NOT EDIT.
package mg6

import (
	"bytes"
	"encoding/binary"
	"github.com/cedws/w101-client-go/codegen"
	"github.com/cedws/w101-client-go/proto"
)

type service interface {
	MG6Connect(MG6Connect)
	MG6Moved(MG6Moved)
	MG6Rewards(MG6Rewards)
}

func (Service) MG6Connect(MG6Connect) {}
func (Service) MG6Moved(MG6Moved)     {}
func (Service) MG6Rewards(MG6Rewards) {}

func RegisterService(r *proto.MessageRouter, s service) {
	proto.RegisterMessageHandler(r, 47, 1, s.MG6Connect)
	proto.RegisterMessageHandler(r, 47, 2, s.MG6Moved)
	proto.RegisterMessageHandler(r, 47, 3, s.MG6Rewards)
}

func NewClient(c *proto.Client) Client {
	return Client{c}
}

func (c Client) MG6Connect(m *MG6Connect) error {
	return c.c.WriteMessage(47, 1, m)
}

func (c Client) MG6Moved(m *MG6Moved) error {
	return c.c.WriteMessage(47, 2, m)
}

func (c Client) MG6Rewards(m *MG6Rewards) error {
	return c.c.WriteMessage(47, 3, m)
}

type Service struct {
	service
}

type Client struct {
	c *proto.Client
}
type MG6Connect struct {
}

func (s *MG6Connect) Marshal() []byte {
	return []byte{}
}

func (s *MG6Connect) Unmarshal(data []byte) error {
	return nil
}

type MG6Moved struct {
}

func (s *MG6Moved) Marshal() []byte {
	return []byte{}
}

func (s *MG6Moved) Unmarshal(data []byte) error {
	return nil
}

type MG6Rewards struct {
	GameName string
	Score    int32
}

func (s *MG6Rewards) Marshal() []byte {
	b := bytes.NewBuffer(make([]byte, 0, 6+len(s.GameName)))
	binary.Write(b, binary.LittleEndian, s.Score)
	codegen.WriteString(b, s.GameName)
	return b.Bytes()
}

func (s *MG6Rewards) Unmarshal(data []byte) error {
	b := bytes.NewReader(data)
	var err error
	if err = binary.Read(b, binary.LittleEndian, &s.Score); err != nil {
		return err
	}
	if s.GameName, err = codegen.ReadString(b); err != nil {
		return err
	}
	return nil
}
