// Code generated by w101-client-go. DO NOT EDIT.
package mg5

import (
	"bytes"
	"encoding/binary"
	"github.com/cedws/w101-client-go/codegen"
	"github.com/cedws/w101-client-go/proto"
)

type service interface {
	MG5Connect(MG5Connect)
	MG5Moved(MG5Moved)
	MG5Rewards(MG5Rewards)
}

func (Service) MG5Connect(MG5Connect) {}
func (Service) MG5Moved(MG5Moved)     {}
func (Service) MG5Rewards(MG5Rewards) {}

func RegisterService(r *proto.MessageRouter, s service) {
	proto.RegisterMessageHandler(r, 46, 1, s.MG5Connect)
	proto.RegisterMessageHandler(r, 46, 2, s.MG5Moved)
	proto.RegisterMessageHandler(r, 46, 3, s.MG5Rewards)
}

func NewClient(c *proto.Client) Client {
	return Client{c}
}

func (c Client) MG5Connect(m *MG5Connect) error {
	return c.c.WriteMessage(46, 1, m)
}

func (c Client) MG5Moved(m *MG5Moved) error {
	return c.c.WriteMessage(46, 2, m)
}

func (c Client) MG5Rewards(m *MG5Rewards) error {
	return c.c.WriteMessage(46, 3, m)
}

type Service struct {
	service
}

type Client struct {
	c *proto.Client
}
type MG5Connect struct {
}

func (s *MG5Connect) Marshal() []byte {
	return []byte{}
}

func (s *MG5Connect) Unmarshal(data []byte) error {
	return nil
}

type MG5Moved struct {
}

func (s *MG5Moved) Marshal() []byte {
	return []byte{}
}

func (s *MG5Moved) Unmarshal(data []byte) error {
	return nil
}

type MG5Rewards struct {
	GameName string
	Score    int32
}

func (s *MG5Rewards) Marshal() []byte {
	b := bytes.NewBuffer(make([]byte, 0, 6+len(s.GameName)))
	binary.Write(b, binary.LittleEndian, s.Score)
	codegen.WriteString(b, s.GameName)
	return b.Bytes()
}

func (s *MG5Rewards) Unmarshal(data []byte) error {
	b := bytes.NewReader(data)
	var err error
	if err = binary.Read(b, binary.LittleEndian, &s.Score); err != nil {
		return err
	}
	if s.GameName, err = codegen.ReadString(b); err != nil {
		return err
	}
	return nil
}
