// Code generated by w101-client-go. DO NOT EDIT.
package skullriders

import (
	"bytes"
	"encoding/binary"
	"github.com/cedws/w101-client-go/codegen"
	"github.com/cedws/w101-client-go/proto"
)

type service interface {
	SkullRidersConnect(SkullRidersConnect)
	SkullRidersMoved(SkullRidersMoved)
	SkullRidersRewards(SkullRidersRewards)
}

func (Service) SkullRidersConnect(SkullRidersConnect) {}
func (Service) SkullRidersMoved(SkullRidersMoved)     {}
func (Service) SkullRidersRewards(SkullRidersRewards) {}

func RegisterService(r *proto.MessageRouter, s service) {
	proto.RegisterMessageHandler(r, 40, 1, s.SkullRidersConnect)
	proto.RegisterMessageHandler(r, 40, 2, s.SkullRidersMoved)
	proto.RegisterMessageHandler(r, 40, 3, s.SkullRidersRewards)
}

func NewClient(c *proto.Client) Client {
	return Client{c}
}

func (c Client) SkullRidersConnect(m *SkullRidersConnect) error {
	return c.c.WriteMessage(40, 1, m)
}

func (c Client) SkullRidersMoved(m *SkullRidersMoved) error {
	return c.c.WriteMessage(40, 2, m)
}

func (c Client) SkullRidersRewards(m *SkullRidersRewards) error {
	return c.c.WriteMessage(40, 3, m)
}

type Service struct {
	service
}

type Client struct {
	c *proto.Client
}
type SkullRidersConnect struct {
}

func (s *SkullRidersConnect) Marshal() []byte {
	return []byte{}
}

func (s *SkullRidersConnect) Unmarshal(data []byte) error {
	return nil
}

type SkullRidersMoved struct {
}

func (s *SkullRidersMoved) Marshal() []byte {
	return []byte{}
}

func (s *SkullRidersMoved) Unmarshal(data []byte) error {
	return nil
}

type SkullRidersRewards struct {
	GameName string
	Score    int32
}

func (s *SkullRidersRewards) Marshal() []byte {
	b := bytes.NewBuffer(make([]byte, 0, 6+len(s.GameName)))
	binary.Write(b, binary.LittleEndian, s.Score)
	codegen.WriteString(b, s.GameName)
	return b.Bytes()
}

func (s *SkullRidersRewards) Unmarshal(data []byte) error {
	b := bytes.NewReader(data)
	var err error
	if err = binary.Read(b, binary.LittleEndian, &s.Score); err != nil {
		return err
	}
	if s.GameName, err = codegen.ReadString(b); err != nil {
		return err
	}
	return nil
}
