// Code generated by w101-client-go. DO NOT EDIT.
package mg3

import (
	"bytes"
	"encoding/binary"
	"github.com/cedws/w101-client-go/codegen"
	"github.com/cedws/w101-client-go/proto"
)

type service interface {
	MG3Connect(MG3Connect)
	MG3Moved(MG3Moved)
	MG3Rewards(MG3Rewards)
}

func (Service) MG3Connect(MG3Connect) {}
func (Service) MG3Moved(MG3Moved)     {}
func (Service) MG3Rewards(MG3Rewards) {}

func RegisterService(r *proto.MessageRouter, s service) {
	proto.RegisterMessageHandler(r, 44, 1, s.MG3Connect)
	proto.RegisterMessageHandler(r, 44, 2, s.MG3Moved)
	proto.RegisterMessageHandler(r, 44, 3, s.MG3Rewards)
}

func NewClient(c *proto.Client) Client {
	return Client{c}
}

func (c Client) MG3Connect(m *MG3Connect) error {
	return c.c.WriteMessage(44, 1, m)
}

func (c Client) MG3Moved(m *MG3Moved) error {
	return c.c.WriteMessage(44, 2, m)
}

func (c Client) MG3Rewards(m *MG3Rewards) error {
	return c.c.WriteMessage(44, 3, m)
}

type Service struct {
	service
}

type Client struct {
	c *proto.Client
}
type MG3Connect struct {
}

func (s *MG3Connect) Marshal() []byte {
	return []byte{}
}

func (s *MG3Connect) Unmarshal(data []byte) error {
	return nil
}

type MG3Moved struct {
}

func (s *MG3Moved) Marshal() []byte {
	return []byte{}
}

func (s *MG3Moved) Unmarshal(data []byte) error {
	return nil
}

type MG3Rewards struct {
	GameName string
	Score    int32
}

func (s *MG3Rewards) Marshal() []byte {
	b := bytes.NewBuffer(make([]byte, 0, 6+len(s.GameName)))
	binary.Write(b, binary.LittleEndian, s.Score)
	codegen.WriteString(b, s.GameName)
	return b.Bytes()
}

func (s *MG3Rewards) Unmarshal(data []byte) error {
	b := bytes.NewReader(data)
	var err error
	if err = binary.Read(b, binary.LittleEndian, &s.Score); err != nil {
		return err
	}
	if s.GameName, err = codegen.ReadString(b); err != nil {
		return err
	}
	return nil
}
